

----ADD PRIMARY KEY



--[INVENTARIO]
ALTER TABLE [Inventory].[INVENTARIO]
ADD PRIMARY KEY ([ID_INVENTARIO]);

--[CLIENTE]
ALTER TABLE [Person].[CLIENTE]
ADD PRIMARY KEY ([ID_CLIENTE]);

--[EMPLEADO]
ALTER TABLE [Person].[EMPLEADO]
ADD PRIMARY KEY ([ID_EMPLEADO]);

--[CATEGORIA_PRODUCTO]
ALTER TABLE [Product].[CATEGORIA_PRODUCTO]
ADD PRIMARY KEY ([ID_CATEGORIA_PRODUCTO]);

--[PRODUCTO]
ALTER TABLE [Product].[PRODUCTO]
ADD PRIMARY KEY ([ID_PRODUCTO]);

--[COMPRA]
ALTER TABLE [Sales].[COMPRA]
ADD PRIMARY KEY ([ID_COMPRA]);

--[DETALLE_COMPRA]
ALTER TABLE [Sales].[DETALLE_COMPRA]
ADD PRIMARY KEY ([ID_DETALLE_COMPRA]);

--[DETALLE_VENTA]
ALTER TABLE [Sales].[DETALLE_VENTA]
ADD PRIMARY KEY ([ID_DETALLE_VENTA]);


--[VENTA]
ALTER TABLE [Sales].[VENTA]
ADD PRIMARY KEY ([ID_VENTA]);


--[PROVEEDOR]
ALTER TABLE [Supplies].[PROVEEDOR]
ADD PRIMARY KEY ([ID_PROVEEDOR]);



