

----ADD PRIMARY KEY



--[INVENTARIO]
ALTER TABLE [Inventory].[INVENTARIO]
ADD CONSTRAINT PK_ID_INVENTARIO PRIMARY KEY ([ID_INVENTARIO]);

--[CLIENTE]
ALTER TABLE [Person].[CLIENTE]
ADD CONSTRAINT PK_ID_CLIENTE PRIMARY KEY ([ID_CLIENTE]);

--[EMPLEADO]
ALTER TABLE [Person].[EMPLEADO]
ADD CONSTRAINT PK_ID_EMPLEADO PRIMARY KEY ([ID_EMPLEADO]);

--[CATEGORIA_PRODUCTO]
ALTER TABLE [Product].[CATEGORIA_PRODUCTO]
ADD CONSTRAINT PK_ID_CATEGORIA_PRODUCTO PRIMARY KEY ([ID_CATEGORIA_PRODUCTO]);

--[PRODUCTO]
ALTER TABLE [Product].[PRODUCTO]
ADD  CONSTRAINT PK_ID_PRODUCTO PRIMARY KEY ([ID_PRODUCTO]);

--[COMPRA]
ALTER TABLE [Sales].[COMPRA]
ADD CONSTRAINT PK_ID_COMPRA PRIMARY KEY ([ID_COMPRA]);

--[DETALLE_COMPRA]
ALTER TABLE [Sales].[DETALLE_COMPRA]
ADD CONSTRAINT PK_ID_DETALLE_COMPRA PRIMARY KEY ([ID_DETALLE_COMPRA]);

--[DETALLE_VENTA]
ALTER TABLE [Sales].[DETALLE_VENTA]
ADD CONSTRAINT PK_ID_DETALLE_VENTA PRIMARY KEY ([ID_DETALLE_VENTA]);


--[VENTA]
ALTER TABLE [Sales].[VENTA]
ADD CONSTRAINT PK_ID_VENTA PRIMARY KEY ([ID_VENTA]);


--[PROVEEDOR]
ALTER TABLE [Supplies].[PROVEEDOR]
ADD  CONSTRAINT PK_ID_PROVEEDOR PRIMARY KEY ([ID_PROVEEDOR]);



