

USE [PuntoVenta]

--CREATE SCHEMA Person
--CREATE SCHEMA Product
--CREATE SCHEMA Sales
--CREATE SCHEMA [Inventory]
--CREATE SCHEMA [Supplies]



--EMPLEADO
CREATE TABLE [PuntoVenta].[Person].[EMPLEADO](
	ID_EMPLEADO varchar(50) NOT NULL
	,NOMBRE_EMPLEADO VARCHAR(50) NOT NULL
	,ROL_EMPLEADO VARCHAR(20) NOT NULL
	,CLAVE_EMPLEADO VARCHAR(20)
	,ESTADO_CIVIL_EMPLEADO VARCHAR(10)
)

--CLIENTE
CREATE TABLE [PuntoVenta].[Person].CLIENTE(
	ID_CLIENTE VARCHAR(50) NOT NULL
	,NOMBRE_CLIENTE VARCHAR(50) NOT NULL
	,TELEFONO_CLIENTE INT
	,DIRECCION_CLIENTE VARCHAR(50)
	,HISTORIAL_COMPRAS VARCHAR(50) --(relacionado con ventas)
)

--PRODUCTO
CREATE TABLE [PuntoVenta].[Product].PRODUCTO(
	ID_PRODUCTO INT IDENTITY
	,NOMBRE_PRODUCTO VARCHAR(50) NOT NULL
	,DESCRIPCION_PRODUCTO VARCHAR(50)
	,PRECIO_PRODUCTO FLOAT NOT NULL
	,STOCK_PRODUCTO INT		--(cant disponible)
	,CATEGORIA_PRODUCTO VARCHAR(50)
	,CODIGO_BARRA VARCHAR(100)	NULL --(opcional)
)

--CATEGORIA PRODUCTO
CREATE TABLE [PuntoVenta].[Product].CATEGORIA_PRODUCTO(
	ID_CATEGORIA_PRODUCTO INT IDENTITY
	,NOMBRE_CATEGORIA_PRODUCTO VARCHAR(50)
	,DESCRIPCION_CATEGORIA_PRODUCTO VARCHAR(50)
)

--VENTAS
CREATE TABLE [PuntoVenta].[Sales].VENTA(
	ID_VENTA INT IDENTITY
	,FECHA_HORA DATETIME
	,ID_CLIENTE VARCHAR(50)   --(Hasta ahora permitirE Nulos)
	,ID_VENDEDOR VARCHAR(50)  --(ID del empleado que vendiO el producto)
	,TOTAL_VENTA FLOAT        --(Total precio)
	,METODO_PAGO VARCHAR(20)
)

--DETALLE VENTAS
CREATE TABLE [PuntoVenta].[Sales].DETALLE_VENTA(
	ID_DETALLE_VENTA INT IDENTITY
	,ID_VENTA VARCHAR(50) NOT NULL
	,ID_PRODUCTO VARCHAR(50) NOT NULL
	,CANTIDAD_VENDIDA FLOAT
	,PRECIO_UNITARIO FLOAT
	,SUBTOTAL FLOAT
)

--INVENTARIO
CREATE TABLE [PuntoVenta].[Inventory].INVENTARIO(
	ID_INVENTARIO INT IDENTITY
	,ID_PRODUCTO VARCHAR(50)
	,TIPO_MOVIMIENTO VARCHAR(20)	--(Entrada/salida)
	,CANTIDAD INT
	,FECHA DATETIME
	,MOTIVO VARCHAR(50)				---(compra, ajuste, devolucion)
)

--PROVEEDOR
CREATE TABLE [PuntoVenta].[Supplies].[PROVEEDOR](
	ID_PROVEEDOR INT IDENTITY
	,NOMBRE VARCHAR(20)
	,TELEFONO INT
	,DIRECCION VARCHAR(50)
)

--COMPRA  (ENTRADA DE PRODUCTO POR PROVEEDOR)
CREATE TABLE [PuntoVenta].[Sales].[COMPRA](
	ID_COMPRA INT IDENTITY
	,FECHA DATETIME
	,ID_PROVEEDOR INT
	,TOTAL FLOAT
	,USUARIO_REGISTRO_COMPRA VARCHAR(50)
)

--DETALLE_COMPRA
CREATE TABLE [PuntoVenta].[Sales].[DETALLE_COMPRA](
	ID_DETALLE_COMPRA INT
	,ID_COMPRA INT
	,ID_PRODUCTO INT
	,CANTIDAD FLOAT
	,PRECIO_UNITARIO FLOAT
)
