USE PuntoVenta


--INVENTARIO
CREATE TABLE INVENTARIO(
	ID_INVENTARIO INT IDENTITY(1,1)
	,NOMBRE VARCHAR(20) NOT NULL
	,PROVEEDOR VARCHAR(50)
	,CATEGORIA VARCHAR(50)
	,PRECIO FLOAT
	,COSTO FLOAT
	,STOCK INT
)
ALTER TABLE INVENTARIO ADD CONSTRAINT PK_ID_INVENTARIO PRIMARY KEY(ID_INVENTARIO)



--CLIENTE
CREATE TABLE CLIENTE(
	ID_CLIENTE INT IDENTITY 
	,NOMBRE_CLIENTE VARCHAR(20)
	,CEDULA INT
	,CELULAR INT
	,DIRECCION VARCHAR(50)
	,CORREO VARCHAR(50)
)
ALTER TABLE CLIENTE ADD CONSTRAINT PK_ID_CLIENTE PRIMARY KEY(ID_CLIENTE)


--VENTAS
CREATE TABLE VENTAS(
	FACTURA INT
	,CLIENTE VARCHAR(50)
	,PRODUCTO VARCHAR(50)
	,PRECIO FLOAT
	,CANTIDAD INT
	,TOTAL FLOAT
	,FECHA VARCHAR(20)
	,HORA VARCHAR(20)
	,COSTO VARCHAR(20)
)


--USUARIOS
CREATE TABLE USUARIO(
	ID_USUARIO INT NOT NULL 
	,USERNAME VARCHAR(20) NOT NULL
	,USER_PASSWORD VARCHAR(50) NOT NULL
)
ALTER TABLE USUARIO ADD CONSTRAINT PK_ID_USUARIO PRIMARY KEY(ID_USUARIO)